/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocialNetworkPackage;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Henry
 */
public class SocialNetwork_Form extends javax.swing.JFrame {

    private Network_Handler handler = new Network_Handler();
    Profile currentProfile = null;
    
    private void displayProfile()
    {   
        nameText.setText(currentProfile.getName());
        statusTextField.setText(currentProfile.getStatus());
        
        ArrayList<String> s = currentProfile.getFriends();
        if (s.size() == 0)
            friendsListArea.setText("no friends");
        else
        {
            StringBuilder sList = new StringBuilder();
            for (int i = 0; i < s.size(); i++)
            {
                sList.append(s.get(i));
                sList.append("\n");
            }
            friendsListArea.setText(sList.toString());
        }
        
    }
    
        //asks user to close program
    private void terminateApplication()
    {
        int response = JOptionPane.NO_OPTION;
        String prompt = "Are you sure you want to quit WUPHF?";
        String title = "Quit WUPHF";
        response = JOptionPane.showConfirmDialog(null, prompt, title, JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }  
    
    /**
     * Creates new form SocialNetwork_Form
     */
    public SocialNetwork_Form() {
        initComponents();
        setLocationRelativeTo(null);
        statusTextField.setEditable(false);
        friendsListArea.setEditable(false);
        logoutButton.setEnabled(false);
        deleteAccMenuItem.setEnabled(false);
        createProfMenuItem.setEnabled(false);
        modifyProfMenuItem.setEnabled(false);
        searchfrMenuItem.setEnabled(false);
        nameText.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        friendsListArea = new javax.swing.JTextArea();
        nameText = new javax.swing.JTextField();
        logoutButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        accountMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        createAccMenuItem = new javax.swing.JMenuItem();
        deleteAccMenuItem = new javax.swing.JMenuItem();
        profileMenu = new javax.swing.JMenu();
        createProfMenuItem = new javax.swing.JMenuItem();
        modifyProfMenuItem = new javax.swing.JMenuItem();
        searchfrMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WUPHF Social Network");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("              Friends");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Welcome to");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        jLabel3.setText("WUPHF");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Your Status:");

        statusTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawprint.PNG"))); // NOI18N
        jLabel5.setText("jLabel5");

        friendsListArea.setColumns(20);
        friendsListArea.setRows(5);
        jScrollPane2.setViewportView(friendsListArea);

        nameText.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        nameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameText.setText("Anonymous!");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        accountMenu.setText("Account");

        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        accountMenu.add(loginMenuItem);

        createAccMenuItem.setText("Create Account");
        createAccMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccMenuItemActionPerformed(evt);
            }
        });
        accountMenu.add(createAccMenuItem);

        deleteAccMenuItem.setText("Delete Account");
        deleteAccMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccMenuItemActionPerformed(evt);
            }
        });
        accountMenu.add(deleteAccMenuItem);

        jMenuBar1.add(accountMenu);

        profileMenu.setText("Profile");

        createProfMenuItem.setText("Create Profile");
        createProfMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfMenuItemActionPerformed(evt);
            }
        });
        profileMenu.add(createProfMenuItem);

        modifyProfMenuItem.setText("Modify Profile");
        modifyProfMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyProfMenuItemActionPerformed(evt);
            }
        });
        profileMenu.add(modifyProfMenuItem);

        searchfrMenuItem.setText("Search friend");
        searchfrMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfrMenuItemActionPerformed(evt);
            }
        });
        profileMenu.add(searchfrMenuItem);

        jMenuBar1.add(profileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel2)))
                                .addGap(195, 195, 195)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(155, 155, 155)
                                        .addComponent(jLabel4))
                                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
        // TODO add your handling code here:
        String loginName = JOptionPane.showInputDialog("What is your login name?");
        currentProfile = handler.getProfile(loginName);
        if(currentProfile == null)
            JOptionPane.showMessageDialog(null, "Account not Found");
        else
        {
            displayProfile();
            loginMenuItem.setEnabled(false);
            createAccMenuItem.setEnabled(false);
            deleteAccMenuItem.setEnabled(true);
            createProfMenuItem.setEnabled(false);
            modifyProfMenuItem.setEnabled(true);
            searchfrMenuItem.setEnabled(true);
            logoutButton.setEnabled(true);
        }
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void deleteAccMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccMenuItemActionPerformed
        // TODO add your handling code here:
        
        int decision = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this account?");
        
        if (decision == 2)
        {
            // do nothing
        }
        else if (decision == 1)
        {
            // do nothing
        }
        else
        {
            handler.deleteAccount(currentProfile.getName());
            
            loginMenuItem.setEnabled(true);
            createAccMenuItem.setEnabled(true);
            deleteAccMenuItem.setEnabled(false);
            createProfMenuItem.setEnabled(false);
            modifyProfMenuItem.setEnabled(false);
            searchfrMenuItem.setEnabled(false);
            logoutButton.setEnabled(false);
            
            nameText.setText("Anonymous!");
            friendsListArea.setText("no friends");
            statusTextField.setText("");
        }
        
    }//GEN-LAST:event_deleteAccMenuItemActionPerformed

    private void statusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextFieldActionPerformed

    private void modifyProfMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyProfMenuItemActionPerformed
        // TODO add your handling code here:
        
        String updatedStatus = JOptionPane.showInputDialog("Enter your Updated Status");
        currentProfile.setStatus(updatedStatus);
        displayProfile();
        
        loginMenuItem.setEnabled(false);
        createAccMenuItem.setEnabled(false);
        deleteAccMenuItem.setEnabled(true);
        createProfMenuItem.setEnabled(false);
        modifyProfMenuItem.setEnabled(true);
        searchfrMenuItem.setEnabled(true);
        logoutButton.setEnabled(true);
        
    }//GEN-LAST:event_modifyProfMenuItemActionPerformed

    private void createProfMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfMenuItemActionPerformed
        // TODO add your handling code here:
        
        String firstStatus = JOptionPane.showInputDialog("What will be your first status?");
        currentProfile.setStatus(firstStatus);
        displayProfile();
        
    }//GEN-LAST:event_createProfMenuItemActionPerformed

    private void createAccMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccMenuItemActionPerformed
        // TODO add your handling code here:
        String accountName = JOptionPane.showInputDialog("What will your account name be?");
        if (accountName.isEmpty())
            JOptionPane.showMessageDialog(null, "Account not created. No name was input.");
        else
        {
            handler.createAccount(accountName);
            JOptionPane.showMessageDialog(null, "Account Created! You're now logged in!");
            currentProfile = handler.getProfile(accountName);
            if(currentProfile == null)
                JOptionPane.showMessageDialog(null, "Account not Found");
            else
            {
                displayProfile();
                
                loginMenuItem.setEnabled(false);
                createAccMenuItem.setEnabled(false);
                deleteAccMenuItem.setEnabled(true);
                createProfMenuItem.setEnabled(true);
                modifyProfMenuItem.setEnabled(true);
                searchfrMenuItem.setEnabled(true);
                logoutButton.setEnabled(true);
            }
            
        }
    }//GEN-LAST:event_createAccMenuItemActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        nameText.setText("Anonymous!");
        statusTextField.setText("");
        friendsListArea.setText("no friends");
        currentProfile = null;
        
        loginMenuItem.setEnabled(true);
        createAccMenuItem.setEnabled(true);
        deleteAccMenuItem.setEnabled(false);
        createProfMenuItem.setEnabled(false);
        modifyProfMenuItem.setEnabled(false);
        searchfrMenuItem.setEnabled(false);
        logoutButton.setEnabled(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        terminateApplication();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void searchfrMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfrMenuItemActionPerformed
        // TODO add your handling code here:
        String nameSearch = JOptionPane.showInputDialog("Type in name of friend you would like to search for");
        Profile p = handler.getProfile(nameSearch);
        if (p == null)
            JOptionPane.showMessageDialog(null, "Sorry! Friend not Found!");
        else
        {
            String message = p.getName() + " was Found!";
            JOptionPane.showMessageDialog(null, message);
            int decision = JOptionPane.showConfirmDialog(null, "Would you like to add " + 
                    p.getName() + " as a friend?");
            
            if(decision == 2)
            {
                //do nothing
            }
            else if(decision == 1)
            {
                JOptionPane.showMessageDialog(null, "Friend not added.");
            }
            else
            {
                currentProfile.addFriend(p.getName());
                p.addFriend(currentProfile.getName());
                displayProfile();
            }
            
            
        }
    }//GEN-LAST:event_searchfrMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocialNetwork_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocialNetwork_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocialNetwork_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocialNetwork_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocialNetwork_Form().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accountMenu;
    private javax.swing.JMenuItem createAccMenuItem;
    private javax.swing.JMenuItem createProfMenuItem;
    private javax.swing.JMenuItem deleteAccMenuItem;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextArea friendsListArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenuItem modifyProfMenuItem;
    private javax.swing.JTextField nameText;
    private javax.swing.JMenu profileMenu;
    private javax.swing.JMenuItem searchfrMenuItem;
    private javax.swing.JTextField statusTextField;
    // End of variables declaration//GEN-END:variables
}
